#!/usr/bin/env bash
# tests/test-install.sh — fixture test for install.sh's editor/CLI lanes
# (--claude / --cursor / --codex / --gemini).
#
# Runs install.sh against temp target dirs and asserts: the default (no-flags) install is
# unchanged, each flag's expected files land with a GENERATED header, Claude's personas are
# copied byte-for-byte from agents/*.md, a second identical run makes no changes (idempotent),
# and a hand-customized generated file is left alone on rerun (same skip contract the gate
# install already has).
#
# No test framework — plain bash, `bash tests/test-install.sh` is the whole invocation (also
# wired into .github/workflows/ci.yml).
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INSTALL="$ROOT/install.sh"

PASS=0
FAIL=0

pass() { echo "PASS $1"; PASS=$((PASS + 1)); }
fail() { echo "FAIL $1"; FAIL=$((FAIL + 1)); }

assert_file() {
  local desc="$1" path="$2"
  if [[ -f "$path" ]]; then pass "$desc"; else fail "$desc (missing: $path)"; fi
}

assert_contains() {
  local desc="$1" path="$2" needle="$3"
  if [[ -f "$path" ]] && grep -qF "$needle" "$path"; then
    pass "$desc"
  else
    fail "$desc (missing '$needle' in $path)"
  fi
}

tree_hash() {
  find "$1" -type f -print0 | sort -z | xargs -0 cksum | cksum
}

PERSONAS=(apollo artemis diogenes plato socrates)

# ---------------------------------------------------------------------------
# 1. Default (no flags) install is unchanged — gate files land, no editor/CLI dirs appear.
# ---------------------------------------------------------------------------
T1="$(mktemp -d)"
"$INSTALL" "$T1" >/dev/null

assert_file "default install: personas copied to .github/review-agents" "$T1/.github/review-agents/artemis.md"
assert_file "default install: decide_verdict.py copied" "$T1/.github/review-agents/decide_verdict.py"
assert_file "default install: review.yml workflow copied" "$T1/.github/workflows/review.yml"

if [[ ! -e "$T1/.claude" && ! -e "$T1/.cursor" && ! -e "$T1/.agents" && ! -e "$T1/.gemini" ]]; then
  pass "default install: no editor/CLI dirs created without flags"
else
  fail "default install: an editor/CLI dir was created without any flag"
fi
rm -rf "$T1"

# ---------------------------------------------------------------------------
# 2. All four flags together against a fresh target — expected files land.
# ---------------------------------------------------------------------------
T2="$(mktemp -d)"
"$INSTALL" "$T2" --claude --cursor --codex --gemini >/dev/null

for p in "${PERSONAS[@]}"; do
  assert_file "claude: $p.md installed" "$T2/.claude/agents/$p.md"
  if cmp -s "$ROOT/agents/$p.md" "$T2/.claude/agents/$p.md"; then
    pass "claude: $p.md matches agents/$p.md verbatim"
  else
    fail "claude: $p.md differs from agents/$p.md"
  fi

  assert_file "cursor: $p.md generated" "$T2/.cursor/agents/$p.md"
  assert_contains "cursor: $p.md has GENERATED header" "$T2/.cursor/agents/$p.md" "GENERATED by install.sh"
  assert_contains "cursor: $p.md marked readonly" "$T2/.cursor/agents/$p.md" "readonly: true"

  assert_file "codex: $p SKILL.md generated" "$T2/.agents/skills/$p/SKILL.md"
  assert_contains "codex: $p SKILL.md has GENERATED header" "$T2/.agents/skills/$p/SKILL.md" "GENERATED by install.sh"

  assert_file "gemini: $p.toml generated" "$T2/.gemini/commands/$p.toml"
  assert_contains "gemini: $p.toml has GENERATED header" "$T2/.gemini/commands/$p.toml" "GENERATED by install.sh"
done

if python3 -c 'import tomllib' 2>/dev/null; then
  for p in "${PERSONAS[@]}"; do
    if python3 -c "import tomllib,sys; tomllib.load(open(sys.argv[1],'rb'))" "$T2/.gemini/commands/$p.toml" 2>/dev/null; then
      pass "gemini: $p.toml parses as valid TOML"
    else
      fail "gemini: $p.toml is not valid TOML"
    fi
  done
else
  echo "note: python3 tomllib unavailable (needs 3.11+) — skipping TOML parse check, non-fatal"
fi

assert_file "claude: /counsel command generated" "$T2/.claude/commands/counsel.md"
assert_contains "claude: /counsel references \$ARGUMENTS" "$T2/.claude/commands/counsel.md" "\$ARGUMENTS"
assert_contains "claude: /counsel has GENERATED header" "$T2/.claude/commands/counsel.md" "GENERATED by install.sh"

# ---------------------------------------------------------------------------
# 3. Idempotency — an identical second run changes nothing and installs nothing new.
# ---------------------------------------------------------------------------
BEFORE_HASH="$(tree_hash "$T2")"
SECOND_RUN_OUT="$("$INSTALL" "$T2" --claude --cursor --codex --gemini 2>&1)"
AFTER_HASH="$(tree_hash "$T2")"

if [[ "$BEFORE_HASH" == "$AFTER_HASH" ]]; then
  pass "idempotent: second run makes no file changes"
else
  fail "idempotent: second run changed file contents"
fi

if ! grep -q "^install.sh: installed " <<<"$SECOND_RUN_OUT"; then
  pass "idempotent: second run reports no new installs"
else
  fail "idempotent: second run reported a new install"
fi

# ---------------------------------------------------------------------------
# 4. Customization refusal — a hand-edited generated file is left alone and reported skipped.
# ---------------------------------------------------------------------------
echo "-- hand customized --" >> "$T2/.cursor/agents/artemis.md"
CUSTOM_BEFORE="$(cat "$T2/.cursor/agents/artemis.md")"
CUSTOM_RUN_OUT="$("$INSTALL" "$T2" --cursor 2>&1)"
CUSTOM_AFTER="$(cat "$T2/.cursor/agents/artemis.md")"

if [[ "$CUSTOM_BEFORE" == "$CUSTOM_AFTER" ]]; then
  pass "customization refusal: hand-edited .cursor/agents/artemis.md left unchanged"
else
  fail "customization refusal: hand-edited .cursor/agents/artemis.md was overwritten"
fi

if grep -q "cursor/agents/artemis.md" <<<"$CUSTOM_RUN_OUT"; then
  pass "customization refusal: skip reported in install.sh output"
else
  fail "customization refusal: skip not reported in install.sh output"
fi

rm -rf "$T2"

# ---------------------------------------------------------------------------
# 5. Individual flags don't require each other — --gemini alone doesn't touch .claude/.cursor.
# ---------------------------------------------------------------------------
T3="$(mktemp -d)"
"$INSTALL" "$T3" --gemini >/dev/null
assert_file "gemini alone: socrates.toml generated" "$T3/.gemini/commands/socrates.toml"
if [[ ! -e "$T3/.claude" && ! -e "$T3/.cursor" && ! -e "$T3/.agents" ]]; then
  pass "gemini alone: no other tool's dirs created"
else
  fail "gemini alone: another tool's dir was created"
fi
rm -rf "$T3"

# ---------------------------------------------------------------------------
# 6. Adversarial escaping fixture — a persona whose description AND body
#    contain a backslash, an embedded double quote, and a literal triple-
#    quote ("""). This is the exact input class an audit proved broke the
#    --gemini generator: persona_body was written into a TOML basic
#    multi-line """ string unescaped, so a backslash (e.g. a Windows path
#    like C:\Users\name) or an embedded """ produced invalid TOML that
#    install.sh still reported as installed, exit 0. The --cursor/--codex
#    YAML frontmatter `description:` had the same gap. Both lanes must now
#    emit content that parses AND round-trips the source value byte-for-byte.
#
#    install.sh always globs $SCRIPT_DIR/agents/*.md, so to exercise the
#    generators against a synthetic persona (not one of the shipped five)
#    without touching this repo's real agents/ dir, this builds a throwaway
#    sibling "repo" — a copy of install.sh next to an agents/ dir holding the
#    five real personas plus the fixture — and runs that copy.
# ---------------------------------------------------------------------------
FIXTURE_ROOT="$(mktemp -d)"
mkdir -p "$FIXTURE_ROOT/agents"
cp "$INSTALL" "$FIXTURE_ROOT/install.sh"
ln -s "$ROOT/action" "$FIXTURE_ROOT/action"
cp "$ROOT/REVIEW_RULES.example.md" "$FIXTURE_ROOT/REVIEW_RULES.example.md"
cp "$ROOT"/agents/*.md "$FIXTURE_ROOT/agents/"

FIXTURE_PERSONA="$FIXTURE_ROOT/agents/fixture-escape.md"
FIXTURE_DESC='fixture desc: has a colon, a backslash \ and "quotes" and a triple """ end'
cat > "$FIXTURE_PERSONA" <<EOF
---
name: fixture-escape
description: $FIXTURE_DESC
model: sonnet
---

Windows path example: C:\Users\name
A line with a quote: she said "hi" to him.
A raw triple-quote marker: """ should not break the wrapping string.
EOF

T6="$(mktemp -d)"
"$FIXTURE_ROOT/install.sh" "$T6" --gemini --cursor --codex >/dev/null 2>&1

assert_file "fixture: gemini toml generated" "$T6/.gemini/commands/fixture-escape.toml"
assert_file "fixture: cursor md generated" "$T6/.cursor/agents/fixture-escape.md"
assert_file "fixture: codex SKILL.md generated" "$T6/.agents/skills/fixture-escape/SKILL.md"

if python3 -c 'import tomllib' 2>/dev/null; then
  if FIXTURE_TARGET="$T6" FIXTURE_DESC="$FIXTURE_DESC" python3 - <<'PYEOF'
import os
import sys
import tomllib

target = os.environ["FIXTURE_TARGET"]
expected_desc = os.environ["FIXTURE_DESC"]
expected_body = (
    "\n"
    "Windows path example: C:\\Users\\name\n"
    "A line with a quote: she said \"hi\" to him.\n"
    "A raw triple-quote marker: \"\"\" should not break the wrapping string.\n"
)
expected_prompt = expected_body + "\nReference under review: {{args}}\n"

try:
    with open(f"{target}/.gemini/commands/fixture-escape.toml", "rb") as f:
        data = tomllib.load(f)
    assert data["description"] == expected_desc
    assert data["prompt"] == expected_prompt
except Exception as exc:  # noqa: BLE001
    print(f"FIXTURE_TOML_FAIL {exc}", file=sys.stderr)
    sys.exit(1)
PYEOF
  then
    pass "fixture: gemini toml parses AND description+prompt round-trip byte-identical"
  else
    fail "fixture: gemini toml failed to parse or round-trip"
  fi
else
  echo "note: python3 tomllib unavailable (needs 3.11+) — skipping fixture TOML check, non-fatal"
fi

if python3 -c 'import yaml' 2>/dev/null; then
  if FIXTURE_TARGET="$T6" FIXTURE_DESC="$FIXTURE_DESC" python3 - <<'PYEOF'
import os
import sys
import yaml

target = os.environ["FIXTURE_TARGET"]
expected_desc = os.environ["FIXTURE_DESC"]

paths = [
    f"{target}/.cursor/agents/fixture-escape.md",
    f"{target}/.agents/skills/fixture-escape/SKILL.md",
]
try:
    for path in paths:
        text = open(path).read()
        frontmatter = text.split("---\n", 2)[1]
        data = yaml.safe_load(frontmatter)
        assert data["description"] == expected_desc, (path, data["description"])
except Exception as exc:  # noqa: BLE001
    print(f"FIXTURE_YAML_FAIL {exc}", file=sys.stderr)
    sys.exit(1)
PYEOF
  then
    pass "fixture: cursor+codex YAML frontmatter parses AND description round-trips byte-identical"
  else
    fail "fixture: cursor+codex YAML frontmatter failed to parse or round-trip"
  fi
else
  echo "note: python3 yaml (PyYAML) unavailable — skipping fixture YAML check, non-fatal"
fi

rm -rf "$FIXTURE_ROOT" "$T6"

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo
echo "install.sh fixtures: $PASS passed, $FAIL failed"
[[ "$FAIL" -eq 0 ]]
