#!/usr/bin/env bash
# tests/test-install.sh — fixture test for install.sh's editor/CLI lanes
# (--claude / --cursor / --codex / --gemini).
#
# Runs install.sh against temp target dirs and asserts: the default (no-flags) install is
# unchanged, each flag's expected files land with a GENERATED header, Claude's personas are
# copied byte-for-byte from agents/*.md, a second identical run makes no changes (idempotent),
# and a hand-customized generated file is left alone on rerun (same skip contract the gate
# install already has).
#
# No test framework — plain bash, `bash tests/test-install.sh` is the whole invocation (also
# wired into .github/workflows/ci.yml).
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INSTALL="$ROOT/install.sh"

PASS=0
FAIL=0

pass() { echo "PASS $1"; PASS=$((PASS + 1)); }
fail() { echo "FAIL $1"; FAIL=$((FAIL + 1)); }

assert_file() {
  local desc="$1" path="$2"
  if [[ -f "$path" ]]; then pass "$desc"; else fail "$desc (missing: $path)"; fi
}

assert_contains() {
  local desc="$1" path="$2" needle="$3"
  if [[ -f "$path" ]] && grep -qF "$needle" "$path"; then
    pass "$desc"
  else
    fail "$desc (missing '$needle' in $path)"
  fi
}

tree_hash() {
  find "$1" -type f -print0 | sort -z | xargs -0 cksum | cksum
}

PERSONAS=(apollo artemis diogenes plato socrates)

# ---------------------------------------------------------------------------
# 1. Default (no flags) install is unchanged — gate files land, no editor/CLI dirs appear.
# ---------------------------------------------------------------------------
T1="$(mktemp -d)"
"$INSTALL" "$T1" >/dev/null

assert_file "default install: personas copied to .github/review-agents" "$T1/.github/review-agents/artemis.md"
assert_file "default install: decide_verdict.py copied" "$T1/.github/review-agents/decide_verdict.py"
assert_file "default install: review.yml workflow copied" "$T1/.github/workflows/review.yml"

if [[ ! -e "$T1/.claude" && ! -e "$T1/.cursor" && ! -e "$T1/.agents" && ! -e "$T1/.gemini" ]]; then
  pass "default install: no editor/CLI dirs created without flags"
else
  fail "default install: an editor/CLI dir was created without any flag"
fi
rm -rf "$T1"

# ---------------------------------------------------------------------------
# 2. All four flags together against a fresh target — expected files land.
# ---------------------------------------------------------------------------
T2="$(mktemp -d)"
"$INSTALL" "$T2" --claude --cursor --codex --gemini >/dev/null

for p in "${PERSONAS[@]}"; do
  assert_file "claude: $p.md installed" "$T2/.claude/agents/$p.md"
  if cmp -s "$ROOT/agents/$p.md" "$T2/.claude/agents/$p.md"; then
    pass "claude: $p.md matches agents/$p.md verbatim"
  else
    fail "claude: $p.md differs from agents/$p.md"
  fi

  assert_file "cursor: $p.md generated" "$T2/.cursor/agents/$p.md"
  assert_contains "cursor: $p.md has GENERATED header" "$T2/.cursor/agents/$p.md" "GENERATED by install.sh"
  assert_contains "cursor: $p.md marked readonly" "$T2/.cursor/agents/$p.md" "readonly: true"

  assert_file "codex: $p SKILL.md generated" "$T2/.agents/skills/$p/SKILL.md"
  assert_contains "codex: $p SKILL.md has GENERATED header" "$T2/.agents/skills/$p/SKILL.md" "GENERATED by install.sh"

  assert_file "gemini: $p.toml generated" "$T2/.gemini/commands/$p.toml"
  assert_contains "gemini: $p.toml has GENERATED header" "$T2/.gemini/commands/$p.toml" "GENERATED by install.sh"
done

if python3 -c 'import tomllib' 2>/dev/null; then
  for p in "${PERSONAS[@]}"; do
    if python3 -c "import tomllib,sys; tomllib.load(open(sys.argv[1],'rb'))" "$T2/.gemini/commands/$p.toml" 2>/dev/null; then
      pass "gemini: $p.toml parses as valid TOML"
    else
      fail "gemini: $p.toml is not valid TOML"
    fi
  done
else
  echo "note: python3 tomllib unavailable (needs 3.11+) — skipping TOML parse check, non-fatal"
fi

assert_file "claude: /counsel command generated" "$T2/.claude/commands/counsel.md"
assert_contains "claude: /counsel references \$ARGUMENTS" "$T2/.claude/commands/counsel.md" "\$ARGUMENTS"
assert_contains "claude: /counsel has GENERATED header" "$T2/.claude/commands/counsel.md" "GENERATED by install.sh"

# ---------------------------------------------------------------------------
# 3. Idempotency — an identical second run changes nothing and installs nothing new.
# ---------------------------------------------------------------------------
BEFORE_HASH="$(tree_hash "$T2")"
SECOND_RUN_OUT="$("$INSTALL" "$T2" --claude --cursor --codex --gemini 2>&1)"
AFTER_HASH="$(tree_hash "$T2")"

if [[ "$BEFORE_HASH" == "$AFTER_HASH" ]]; then
  pass "idempotent: second run makes no file changes"
else
  fail "idempotent: second run changed file contents"
fi

if ! grep -q "^install.sh: installed " <<<"$SECOND_RUN_OUT"; then
  pass "idempotent: second run reports no new installs"
else
  fail "idempotent: second run reported a new install"
fi

# ---------------------------------------------------------------------------
# 4. Customization refusal — a hand-edited generated file is left alone and reported skipped.
# ---------------------------------------------------------------------------
echo "-- hand customized --" >> "$T2/.cursor/agents/artemis.md"
CUSTOM_BEFORE="$(cat "$T2/.cursor/agents/artemis.md")"
CUSTOM_RUN_OUT="$("$INSTALL" "$T2" --cursor 2>&1)"
CUSTOM_AFTER="$(cat "$T2/.cursor/agents/artemis.md")"

if [[ "$CUSTOM_BEFORE" == "$CUSTOM_AFTER" ]]; then
  pass "customization refusal: hand-edited .cursor/agents/artemis.md left unchanged"
else
  fail "customization refusal: hand-edited .cursor/agents/artemis.md was overwritten"
fi

if grep -q "cursor/agents/artemis.md" <<<"$CUSTOM_RUN_OUT"; then
  pass "customization refusal: skip reported in install.sh output"
else
  fail "customization refusal: skip not reported in install.sh output"
fi

rm -rf "$T2"

# ---------------------------------------------------------------------------
# 5. Individual flags don't require each other — --gemini alone doesn't touch .claude/.cursor.
# ---------------------------------------------------------------------------
T3="$(mktemp -d)"
"$INSTALL" "$T3" --gemini >/dev/null
assert_file "gemini alone: socrates.toml generated" "$T3/.gemini/commands/socrates.toml"
if [[ ! -e "$T3/.claude" && ! -e "$T3/.cursor" && ! -e "$T3/.agents" ]]; then
  pass "gemini alone: no other tool's dirs created"
else
  fail "gemini alone: another tool's dir was created"
fi
rm -rf "$T3"

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo
echo "install.sh fixtures: $PASS passed, $FAIL failed"
[[ "$FAIL" -eq 0 ]]
